### ISSUE TITLE
Due to the use of netty component, the netty.controller.package Property is invalid, causing controller to fail

### ISSUE THREAD

**Issue by 24kGarry** [EdurtIO/incubator-gcm#1]
**Describe the bug**
Due to the use of netty component, the netty.controller.package Property is invalid, causing controller to fail.

**Desktop (please complete the following information):**
 - OS MAC
 - Browser chrome, safari,curl
 - Version 1.0.2

**Comment by qianmoQ** [comment]
this issues is fix please select `1.0.2` version
