### ISSUE TITLE
Optimization of controller adding method

### ISSUE THREAD

**Issue by 24kGarry** [EdurtIO/incubator-gcm#2]
hello, at present DispatchRules.ROUES Method can't be loaded automatically, but it still needs to be written manually. Can we optimize this place?

**Comment by qianmoQ** [comment]
OK, let's optimize this one

**Comment by 24kGarry** [comment]
hope to recive you reply

**Comment by qianmoQ** [comment]
Auto scan is supported. See [commit](https://github.com/EdurtIO/incubator-gcm/commit/0875dd6891dc2b9a2781c5894409e332d785633c) 1.0.5 and later are required.
