### ISSUE TITLE
Bug report for client request parameters cannot be obtained On netty

### ISSUE THREAD

**Issue by GtoCm** [EdurtIO/incubator-gcm#23]
**Describe the bug**
When the back-end restcontroller contains two parameters, requestparam and requestbody, all parameters cannot be resolved

**To Reproduce**

**Expected behavior**

**Screenshots**

**Component (please set component name):**
 - Component: Netty
 - Version: >= 1.0.7

**Additional context**

**Comment by qianmoQ** [comment]
After testing, the problem can not be repeated
