### ISSUE TITLE
Bug report for Nested subclasses cannot be resolved On Netty

### ISSUE THREAD

**Issue by GtoCm** [EdurtIO/incubator-gcm#31]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Component (please set component name):**
 - Component: [e.g. Netty]
 - Version [e.g. 1.0.2]

**Additional context**

**Comment by qianmoQ** [comment]
The problem can not be repeated, and no problem is found after the test. Please refer to the test example [commit](https://github.com/EdurtIO/incubator-gcm/commit/1cde1f4af56291ccccd16b55c620a2743cd65450)
