### ISSUE TITLE
Bug report for Parameter does not support enumeration On Netty

### ISSUE THREAD

**Issue by GtoCm** [EdurtIO/incubator-gcm#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Component (please set component name):**
 - Component: [e.g. Netty]
 - Version [e.g. 1.0.2]

**Additional context**

**Comment by qianmoQ** [comment]
The problem can not be repeated, and no problem is found after the test. Please refer to the test example [commit](https://github.com/EdurtIO/incubator-gcm/commit/ee2f8c1d782f5b0e97a64f066a018969e820a49c)
