### ISSUE TITLE
Bug report for Page does not support static file rendering On Netty

### ISSUE THREAD

**Issue by GtoCm** [EdurtIO/incubator-gcm#36]
**Describe the bug**
Page does not support static file rendering

**To Reproduce**

**Expected behavior**

**Screenshots**

**Component (please set component name):**
 - Component: [e.g. Netty]
 - Version [e.g. 1.0.2]

**Additional context**

**Comment by qianmoQ** [comment]
please see [commit](https://github.com/EdurtIO/incubator-gcm/commit/f1d0797d6c49847e939957b727145ef536817c3d)
