### ISSUE TITLE
Add more basic methods to manipulate redis key/value

### ISSUE THREAD

**Issue by joint-song** [EdurtIO/incubator-gcm#38]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add method like `RedisClient.get(String key) String` to get value for key.
Add method like `RedisClient.set(String key, String value)` to overwrite/set value for key.
Add method like `RedisClient.expire(String key)` to set expiration for key.
Add method like `RedisClient.persist(String key)` to persist key.
Add method like `RedisClient.ttl(String key) Long` to get ttl of key.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by qianmoQ** [comment]
On Support [commit](https://github.com/EdurtIO/incubator-gcm/commit/16d81c1f744141e1f3eef0d96bfe088330f06aa9)
