### ISSUE TITLE
Feature request for support for Boolean request parameter parsing

### ISSUE THREAD

**Issue by joint-song** [EdurtIO/incubator-gcm#39]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
No

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by qianmoQ** [comment]
see [commit](https://github.com/EdurtIO/incubator-gcm/commit/926132bbb6af7e1358063c32f3b31a64722d067e)
