### ISSUE TITLE
Support test case for mysql 'transaction'

### ISSUE THREAD

**Issue by 24kGarry** [EdurtIO/incubator-gcm#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 24kGarry** [comment]
Add something about Guice test case, similar to rollback

**Comment by qianmoQ** [comment]
Support junit component

**Comment by qianmoQ** [comment]
more [MyBatis Test framework](https://gcm.incubator.edurt.io/general/test/mybatis/)
